USE ContactDB;

CREATE TABLE Users (
	UserID				INT 		NOT NULL 	AUTO_INCREMENT,
	FirstName			VARCHAR(50) NOT NULL 	DEFAULT '',
	LastName 			VARCHAR(50) NOT NULL 	DEFAULT '',
	Login				VARCHAR(50) NOT NULL 	DEFAULT '',
	Password			VARCHAR(64) NOT NULL 	DEFAULT '',
	DateCreated 		DATETIME 	NOT NULL 	DEFAULT CURRENT_TIMESTAMP,
	DateLastLoggedIn 	DATETIME 	NOT NULL 	DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (UserID),
    UNIQUE (Login)
) ENGINE = InnoDB;

DESCRIBE Users;