USE ContactDB;

CREATE TABLE Contacts (
	ContactID			INT 		NOT NULL 	AUTO_INCREMENT,
	UserID				INT			NOT NULL	DEFAULT 0,
	FirstName			VARCHAR(50) NOT NULL 	DEFAULT '',
	LastName 			VARCHAR(50) NOT NULL 	DEFAULT '',
	PhoneNumber			VARCHAR(20) NOT NULL 	DEFAULT '',
	Email				VARCHAR(50) NOT NULL 	DEFAULT '',
	PRIMARY KEY (ContactID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
) ENGINE = InnoDB;

DESCRIBE Contacts;